### ISSUE TITLE
为什么这样调用不行啊

### ISSUE THREAD

**Issue by Goend** [HJXTSTU/GO-Design-Pattern#1]
//抽象工厂
	fa:=new(Factory.FactoryA)
	Factory.HJXFactory.CreateDrink(fa).Drink()
	Factory.HJXFactory.CreateFood(fa).Eat()

	fb := new(Factory.FactoryB)
	Factory.HJXFactory.CreateFood(fb).Eat()
	Factory.HJXFactory.CreateDrink(fb).Drink()

**Comment by lkysyzxz** [comment]
这个要理解产品族的概念，就是把大产品和小产品之间的包含关系。要应对的需求一般是客户只需要大产品，并且只理解大产品的描述，而不用关心他具体的组成，具体的组成由具体的工厂决定。这样客户那边的逻辑就不会被工厂这边的改变而改变了。

**Comment by Goend** [comment]
##但是这样就没有利用HJXFactory接口，那这个接口的意义在哪里呢？下面这样调用也可以，我知道本质上没有差别，但设计模式很大一部分都是形式问题，所以有了问题，感谢你的回复，谢谢。
###Factory.HJXFactory.CreateFood(fa).EatTwo()
	Factory.HJXFactory.CreateDrink(fa).Drink()

**Comment by lkysyzxz** [comment]
是啊，HJXFactory和FactoryA有什么区别呢？和Factory有什么区别呢？

**Comment by Goend** [comment]
谢谢，感觉设计模式这块我需要很久才能了解，也很有道理。233 不纠结了

**Comment by Goend** [comment]
[生成器模式UML图](https://user-images.githubusercontent.com/40394339/65824849-ffc19700-e2a1-11e9-93a7-6a8f2ae2ce3f.png)
这样画生成器模式图可是正确的？想用UML图把他们梳理一下 感觉并不好分辨

**Comment by lkysyzxz** [comment]
用专业一点的UML绘图软件吧，比如StarUML

**Comment by Goend** [comment]
[生成器模式UML图](https://user-images.githubusercontent.com/40394339/65827020-74a3c980-e2c0-11e9-9b56-3af72b63e6e4.png)
这下呢？

**Comment by lkysyzxz** [comment]
> [生成器模式UML图](https://user-images.githubusercontent.com/40394339/65827020-74a3c980-e2c0-11e9-9b56-3af72b63e6e4.png)
> 这下呢？
这样也不是不可以，但是不像是Builder，看着更像是要复制实例的模式——原型模式
